title: Azure Functions v1 + EF6 Incidents
description: Debugging host lock leases and EF6 concurrency issues in Azure Functions v1
theme: minima

# main site url (no trailing slash)
url: "https://rithik53.github.io"

# since repo is `azure-functions-ef6-blog-`
baseurl: "/azure-functions-ef6-blog-"
